### ISSUE TITLE
Tested for 2022 season?

### ISSUE THREAD

**Issue by nickmiltgen** [kris71990/nfl#7]
Hey Kris, Wondering if this has been tested for the 2022 NFL season. When I run the script, the output Excel file is fairly empty. Wondering if you have any other ideas. Thanks in advance for your time. -Nick
[Survivor_Pool.xlsx](https://github.com/kris71990/nfl/files/9508623/Survivor_Pool.xlsx)

**Comment by kris71990** [comment]
Hey Nick, 

Looks like the Vegas Insider website that I'm scraping has undergone a wholesale redesign that has broken the scripts. This will require updating the targets in the soup functions, or even using something like Selenium if the website is rendering with JS now. In the past when this has happened I've just changed some simple parameters to target the right elements, but this looks like it might require a more significant update. Unfortunately I didn't have a chance to check up on it prior to the start of the season. 

I might not get to this for a little bit so feel free to contribute if you can!

Kris

**Comment by kris71990** [comment]
See fixes in #8 that resolve scraping issues that were breaking the scripts.
